wallpaper = , /home/mwysk/.dotfiles/redlinux.jpg
splash = false

wallpaper {
    monitor = DP-2
    path = /home/mwysk/.dotfiles/redlinux.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = /home/mwysk/.dotfiles/redlinux.jpg
    fit_mode = cover
}
